name: Repository Events
on: # [push, pull_request, issues]
# Hiermee kan je types mee geven in de events
   push:
   pull_request: 
      types: [ opened, assigned, reopened, synchronize ]
   issues:
       types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$GITHUB_SHA"
          echo "$GITHUB_REF"
      - uses: actions/checkout@v7
      - name: Een random echo laten zien als testing
        run: | 
          echo "Dit is een test om te tonen dat de echo string werkt"
          echo "EVENT=$GITHUB_EVENT_NAME"
          echo "REF=$GITHUB_REF"
          echo "HEAD_REF=$GITHUB_HEAD_REF"
          echo "BASE_REF=$GITHUB_BASE_REF"
          echo "SHA=$GITHUB_SHA"
