name: Manual Triggered
on: 
  workflow_dispatch:
     inputs:
        string:
          description: 'Voer een string in'
          required: true
          default: 'Standaardwaarde'
          type: string
        number:
          description: A number input
          default: 4
          type: number
        option:
          description: "An Options Input"
          required: true
          default: "Option 3"
          type: choice
          options:
            - Option 1
            - Option 2
            - Option 3
        boolean:
          description: A boolean option
          required: false
          type: boolean
        environment:
          description: "Environment"
          type: environment
          required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - name: Toon een bericht
        run: echo "Deze stap is handmatig getriggerd via workflow_dispatch."
      - name: Log Informatie
        run: |
          echo "Ingevoerde string: ${{ github.event.inputs.string }}"
          echo "Ingevoerde nummer: ${{ github.event.inputs.number }}"
          echo "Geselecteerde optie: ${{ github.event.inputs.option }}"
          echo "Boolean waarde: ${{ github.event.inputs.boolean }}"
          echo "Geselecteerde omgeving: ${{ github.event.inputs.environment }}"