name: Variables and Secrets
on: [push]

jobs:
  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.REP_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET IS TRUE
        if: contains(BOOLEAN_SECRET, 'true')
        run: echo "I ran"
      - name: Log Vars
        run: |
          echo '${{ vars.JOB_RUNNER }}'
          echo '${{ vars.REP_LEVEL_VAR }}'
   