name: Workflow Run
on: 
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
    branches:
      - main

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Dit is een test om te tonen dat de echo string werkt""