name: Working Dirs & Shalls
on: [push]
jobs:
  display-working-directory-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Display working directory and fils
      run: |
        pwd
        ls -a
        echo $GITHUB_SHA
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE


  display-working-directory-windows:
    runs-on: windows-latest
    steps:
    - name: Display working directory and fils
      run: |
        pwd
        ls -a
        echo $GITHUB_SHA
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE